[package]
name = "gccrs-bottleboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octorust = "0.1"
tokio-cron-scheduler = "0.7"
